### ISSUE TITLE
Sbot's leveldown doesn't work with Node 64

### ISSUE THREAD

**Issue by rabble** [ssbc/ssb-server#582]
What's with us using a library which doesn't work on the current version of node? How do we fix this?

/usr/local/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/scuttlebot/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/usr/local/lib/node_modules/scuttlebot/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/scuttlebot/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by christianbundy** [comment]
@rabble 

Any chance you've recently downgraded Node (or are using Electron or something)? The error message says that your node modules were installed with ABI 64 but that you're trying to run it with ABI 57. Either way, running `npm rebuild` or `npm install` should resolve the issue. If *those* commands throw an error then we have an incompatibility.

**Comment by cryptix** [comment]
Didn't hit this myself yet but one thing that tripped me in the past was that some modules use `npm run rebuild` instead of `npm rebuild`... Don't remember if it was leveldown or sodium, though.

**Comment by christianbundy** [comment]
I think that's just for Electron apps, since they need to rebuild specifically for Electron's ABI version. It's used in Patchwork and Patchbay, but i don't think (?) that command exists on any of our libraries.

Good info to take note of though!

**Comment by SyarifZapata** [comment]
Im using electron and i get the same problem, i tried `npm install, npm rebuild` and `./node_modules/.bin/electron-rebuild` but nothing works. 
any solution to this. Im new to SSB. thanks.

**Comment by rabble** [comment]
Just for the record, i'm still having this problem, using nvm to change the node version didn't fix it. And this isn't related to the electron app because i'm not touching that, trying to use that, or anything.

**Comment by christianbundy** [comment]
What's the output of `npm rebuild && npm start`?

The error you posted usually means "you ran `npm install` with Node 8 but you're running `npm start` with Node 10".
